### ISSUE TITLE
daemonic processes are not allowed to have children 

### ISSUE THREAD

**Issue by eromoe** [jfloff/alpine-python#14]
Hi, I got below error while using multiprocessing
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/bid/pipeline/app.py", line 121, in task_create
    run_task(config)
  File "/data/bid/pipeline/tasks.py", line 66, in run_task
    run_in_subprocess(_run_task, config)
  File "/data/bid/pipeline/tasks.py", line 27, in run_in_subprocess
    thread.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

relevant code:

```
def run_in_subprocess(func, *args, **kwargs):
    from multiprocessing import Process
    thread = Process(target=func, args=args, kwargs=kwargs)
    thread.daemon = True
    thread.start()
    return thread

```

This error not show in `python:2.7` image.

**Comment by jfloff** [comment]
Were you able to solve this?

**Comment by eromoe** [comment]
I am wrong, this happend in `python:2.7` too.

**Comment by jfloff** [comment]
Thank you for the feedback!
