### ISSUE TITLE
Unable to use python sqlite3

### ISSUE THREAD

**Issue by ColinHuang** [jfloff/alpine-python#37]
Trying to use peewee package with sqlite3 in  jfloff/alpine-python:2.7.

Error:
```
peewee.ImproperlyConfigured: pysqlite or sqlite3 must be installed.
```

If import sqlite3 directly:
```
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7.15/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/lib/python2.7.15/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: Error loading shared library libsqlite3.so.0: No such file or directory (needed by /usr/lib/python2.7.15/lib/python2.7/lib-dynload/_sqlite3.so)
```

**Comment by jfloff** [comment]
For `sqlite` you actually have to install the alpine packages like this: `apk add --update --no-cache sqlite sqlite-dev`

**Comment by jfloff** [comment]
Mmm, I'll do some impact study on the size of the image, but you are right it should have so both versions (3 and 2) stay consistent.
