### ISSUE TITLE
Shared libraries not found since last commit

### ISSUE THREAD

**Issue by slowr** [jfloff/alpine-python#48]
After 3f0751f9f368389fbde77aa3b4a0008ae82720ae all pip packages that use c libraries are broken.
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 18, in <module>
    from pip._internal.download import PipSession
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/download.py", line 38, in <module>
    from pip._internal.utils.glibc import libc_ver
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
    import ctypes
  File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: Error loading shared library libffi.so.6: No such file or directory (needed by /usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by jfloff** [comment]
Hi there! I released a version yesterday with a fix for this. I added the shared libraries and also `libffi-dev`. I ran your import statement `from _ctypes import Union, Structure, Array` and it worked. 

Feel free to reopen if you are still finding some issue. Thanks for the report.
